dbConfig:
  host: 172.28.5.2
  port: 27017
  username: root
  password: toor
  replica: rs0

apiConfig:
  base_uri: 'https://api.etherscan.io/'
  token: '<your api token here>'

serverConfig:
  port: 1323

redisConfig:
  host: 172.28.5.3
  port: 6379