dbConfig:
  host: localhost
  port: 27017
  username: root
  password: toor
  replica: rs0

apiConfig:
  base_uri: 'https://api.etherscan.io/'
  token: '84TFIGZS8D2FH8Y66VAGS895PGPRTAR2VZ'

serverConfig:
  port: 1323