version: "3.1"
services:  
  mongo:
    container_name: mongod-latest
    image: mongo
    network_mode: bridge
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
volumes:
  dbdata6:

  